name: Racket Coverage
on:
  push:
    branches:
      - "*"
    paths:
      - "**coverage.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: x64
          distribution: full
          variant: "CS"
          version: "stable"
          packages: "cover, cover-badge"
      - run: raco pkg install --no-docs --auto --skip-installed
      - run: |
          raco cover -b .
          raco cover-badge
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage
          publish_branch: gh-pages
          destination_dir: coverage
